# Generated by Django 5.2.8 on 2025-12-22 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crmapp', '0015_productalias'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=255)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SavedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('file_path', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HybridRankingDebug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('num_candidates', models.IntegerField(default=0)),
                ('debug_log', models.JSONField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmapp.customer_details')),
            ],
            options={
                'db_table': 'hybrid_ranking_debug',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=128)),
                ('tags', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='crmapp.product')),
            ],
            options={
                'db_table': 'recommender_item',
            },
        ),
        migrations.CreateModel(
            name='PestRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_customer_id', models.CharField(blank=True, db_column='customer_id', max_length=255, null=True)),
                ('recommendation_type', models.CharField(blank=True, choices=[('upsell', 'Upsell'), ('crosssell', 'Cross-sell'), ('content', 'Content-Based'), ('collaborative', 'Collaborative'), ('demographic', 'Demographic')], max_length=20, null=True)),
                ('reco_channel', models.CharField(choices=[('product', 'Product'), ('service', 'Service')], default='product', max_length=20)),
                ('algorithm_strategy', models.CharField(blank=True, max_length=30, null=True)),
                ('model_source', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('final_score', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('priority', models.IntegerField(default=100)),
                ('serving_state', models.CharField(choices=[('pending', 'Pending'), ('served', 'Served'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_recommendations', to='crmapp.product')),
                ('customer', models.ForeignKey(blank=True, db_column='customer_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pest_recommendations', to='crmapp.customer_details')),
                ('recommended_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_products', to='crmapp.product')),
                ('recommended_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_services', to='crmapp.servicecatalog')),
            ],
            options={
                'db_table': 'pest_recommendations',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_customers', to='crmapp.customer_details')),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_products', to='crmapp.product')),
            ],
            options={
                'db_table': 'recommender_rating',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cf', 'Collaborative'), ('content', 'Content Based'), ('upsell', 'Upsell'), ('cross_sell', 'Cross Sell'), ('demographic', 'Demographic'), ('hybrid', 'Hybrid')], max_length=30)),
                ('score', models.FloatField()),
                ('rank', models.IntegerField()),
                ('reason', models.TextField()),
                ('model_version', models.CharField(max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.customer_details')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmapp.product')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmapp.service_management')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('shown', 'Shown'), ('clicked', 'Clicked'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=20)),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.recommendation')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(max_length=30)),
                ('action', models.CharField(choices=[('shown', 'Shown'), ('clicked', 'Clicked'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=20)),
                ('score', models.FloatField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.customer_details')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engines_used', models.JSONField()),
                ('weights', models.JSONField()),
                ('candidate_count', models.IntegerField()),
                ('final_count', models.IntegerField()),
                ('model_version', models.CharField(max_length=50)),
                ('run_time_ms', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.customer_details')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProductSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_count', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_purchased_at', models.DateTimeField(blank=True, null=True)),
                ('recency_score', models.FloatField(default=0)),
                ('frequency_score', models.FloatField(default=0)),
                ('monetary_score', models.FloatField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.customer_details')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.product')),
            ],
            options={
                'indexes': [models.Index(fields=['customer'], name='recommender_custome_7ecce6_idx'), models.Index(fields=['product'], name='recommender_product_839bda_idx')],
                'unique_together': {('customer', 'product')},
            },
        ),
        migrations.CreateModel(
            name='CustomerServiceSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_contract_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contract_type', models.CharField(max_length=50)),
                ('contract_status', models.CharField(max_length=20)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.customer_details')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.service_management')),
            ],
            options={
                'unique_together': {('customer', 'service')},
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('click', 'Click'), ('purchase', 'Purchase'), ('call', 'Call'), ('recommend', 'Recommendation Shown')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interaction_customers', to='crmapp.customer_details')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interaction_products', to='crmapp.product')),
            ],
            options={
                'db_table': 'recommender_interaction',
                'ordering': ['-timestamp'],
                'unique_together': {('customer', 'product', 'interaction_type')},
            },
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['customer'], name='recommender_custome_80ca5c_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['method'], name='recommender_method_a768db_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationlog',
            index=models.Index(fields=['customer', 'product'], name='recommender_custome_17951b_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationlog',
            index=models.Index(fields=['recommendation_type'], name='recommender_recomme_407f16_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationlog',
            index=models.Index(fields=['action'], name='recommender_action_a81cdd_idx'),
        ),
    ]
