# Generated by Django 5.2.8 on 2025-12-22 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0015_productalias'),
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pestrecommendation',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pestrecommendation',
            name='converted_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_recommendations', to='crmapp.product'),
        ),
        migrations.AddField(
            model_name='pestrecommendation',
            name='converted_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_service_recommendations', to='crmapp.servicecatalog'),
        ),
        migrations.AddField(
            model_name='pestrecommendation',
            name='revenue_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
