# Generated by Django 5.2.8 on 2025-12-23 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0015_productalias'),
        ('recommender', '0002_pestrecommendation_converted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pestrecommendation',
            name='action',
            field=models.CharField(choices=[('none', 'None'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('help', 'Help Requested')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='pestrecommendation',
            name='business_intent',
            field=models.CharField(blank=True, choices=[('upsell', 'Upsell'), ('crosssell', 'Cross-sell'), ('retention', 'Retention'), ('reactivation', 'Reactivation')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pestrecommendation',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RecommendationInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.BigIntegerField(blank=True, null=True)),
                ('interaction_type', models.CharField(choices=[('exposed', 'Exposed'), ('viewed', 'Viewed'), ('clicked', 'Clicked'), ('dismissed', 'Dismissed'), ('accepted', 'Accepted'), ('converted', 'Converted')], max_length=20)),
                ('interaction_channel', models.CharField(choices=[('crm', 'CRM'), ('whatsapp', 'WhatsApp'), ('call', 'Call'), ('app', 'App'), ('email', 'Email')], max_length=20)),
                ('event_time', models.DateTimeField()),
                ('exposure_id', models.CharField(blank=True, max_length=64, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.customer_details')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmapp.product')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='recommender.pestrecommendation')),
            ],
            options={
                'db_table': 'recommendation_interactions',
                'indexes': [models.Index(fields=['recommendation', 'interaction_type'], name='recommendat_recomme_996c5f_idx'), models.Index(fields=['customer', 'event_time'], name='recommendat_custome_5274be_idx'), models.Index(fields=['interaction_type', 'event_time'], name='recommendat_interac_dfdcac_idx')],
            },
        ),
    ]
