# Generated by Django 5.2.8 on 2025-12-24 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0015_productalias'),
        ('recommender', '0004_remove_pestrecommendation_responded_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pestrecommendation',
            name='responded_at',
        ),
        migrations.AlterField(
            model_name='pestrecommendation',
            name='base_product',
            field=models.ForeignKey(blank=True, db_column='base_product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_recommendations', to='crmapp.product'),
        ),
        migrations.AlterField(
            model_name='pestrecommendation',
            name='revenue_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pestrecommendation',
            name='serving_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('served', 'Served'), ('exposed', 'Exposed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
