# Generated by Django 5.2.8 on 2025-12-01 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_hybridrankingdebug'),
    ]

    operations = [
    ]
