# Generated by Django 5.2.8 on 2025-12-01 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0006_sentmessagelog'),
        ('recommender', '0005_auto_20251201_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentmessagelog',
            old_name='message_text',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='sentmessagelog',
            old_name='timestamp',
            new_name='sent_at',
        ),
        migrations.RemoveField(
            model_name='sentmessagelog',
            name='api_response',
        ),
        migrations.RemoveField(
            model_name='sentmessagelog',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='sentmessagelog',
            name='message_id',
        ),
        migrations.RemoveField(
            model_name='sentmessagelog',
            name='phone',
        ),
        migrations.AddField(
            model_name='sentmessagelog',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmapp.customer_details'),
        ),
        migrations.AlterField(
            model_name='sentmessagelog',
            name='status',
            field=models.CharField(default='sent', max_length=20),
        ),
    ]
