# Generated by Django 5.2.8 on 2025-12-01 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0006_rename_message_text_sentmessagelog_message_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SentMessageLog',
        ),
    ]
