# Generated by Django 5.2.8 on 2025-12-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0007_delete_sentmessagelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pestrecommendation',
            name='recommendation_type',
            field=models.CharField(blank=True, choices=[('upsell', 'Upsell'), ('crosssell', 'Cross-sell'), ('content', 'Content-Based'), ('collaborative', 'Collaborative'), ('demographic', 'Demographic')], max_length=20, null=True),
        ),
    ]
