# Generated by Django 5.2.8 on 2025-12-16 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0013_servicecatalog'),
        ('recommender', '0008_alter_pestrecommendation_recommendation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pestrecommendation',
            name='recommended_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_services', to='crmapp.servicecatalog'),
        ),
    ]
