# Generated by Django 5.2.8 on 2025-12-01 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0006_sentmessagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentmessagelog',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmapp.customer_details'),
        ),
        migrations.AddField(
            model_name='sentmessagelog',
            name='message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sentmessagelog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sentmessagelog',
            name='provider_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sentmessagelog',
            name='rendered_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sentmessagelog',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('error', 'Error')], default='queued', max_length=50),
        ),
        migrations.AlterField(
            model_name='sentmessagelog',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crmapp.messagetemplates'),
        ),
    ]
