# Generated by Django 5.2.8 on 2025-12-01 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0007_sentmessagelog_customer_sentmessagelog_message_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentmessagelog',
            old_name='sent_at',
            new_name='created_at',
        ),
    ]
