# Generated by Django 5.2.8 on 2025-12-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0008_rename_sent_at_sentmessagelog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentmessagelog',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sentmessagelog',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sentmessagelog',
            name='recommended_product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
