# Generated by Django 5.2.8 on 2025-12-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0010_purchasehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='customer_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='customer_ref',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
