# Generated by Django 5.2.8 on 2025-12-11 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0011_purchasehistory_customer_int_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('3M', '3 Months'), ('6M', '6 Months'), ('AMC', 'AMC')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='crmapp.customer_details')),
            ],
        ),
    ]
