# Generated by Django 5.2.8 on 2025-12-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0012_customercontract'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCatalog',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=255)),
                ('service_category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'service_catalog',
            },
        ),
    ]
