# Generated by Django 5.2.8 on 2025-12-21 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0013_servicecatalog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasehistory',
            options={'ordering': ['-purchased_at']},
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='purchase_type',
            field=models.CharField(choices=[('PRODUCT', 'Product'), ('SERVICE', 'Service')], db_index=True, default='PRODUCT', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_history', to='crmapp.customer_details'),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='customer_int',
            field=models.IntegerField(blank=True, help_text='Legacy integer customer id (DO NOT use for ML)', null=True),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='customer_ref',
            field=models.BigIntegerField(blank=True, help_text='Legacy external customer reference (DO NOT use for ML)', null=True),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_history', to='crmapp.product'),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='purchased_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='purchasehistory',
            index=models.Index(fields=['customer', 'purchased_at'], name='crmapp_purc_custome_44ed1b_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasehistory',
            index=models.Index(fields=['purchase_type'], name='crmapp_purc_purchas_7ccfce_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasehistory',
            index=models.Index(fields=['product'], name='crmapp_purc_product_fcf165_idx'),
        ),
    ]
