# Generated by Django 5.2.8 on 2025-12-21 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0014_alter_purchasehistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(max_length=255, unique=True)),
                ('confidence', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.product')),
            ],
            options={
                'indexes': [models.Index(fields=['alias_name'], name='crmapp_prod_alias_n_1863d8_idx')],
            },
        ),
    ]
