# Generated by Django 5.2.8 on 2025-12-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0015_productalias'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecatalog',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicecatalog',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
